title: <p align="center"> Sajan Kedia </p>
logo: /assets/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/divya-singh-a4161667">LinkedIn</a> |
  <a href="https://github.com/divya4singh">GitHub</a>
  
  <br>   
  I am working with SAP Labs as a Senior Quality Spicialist and an Automation Expert.
  Also doing an Executive PG in AI and ML with IIIT-B.
  <br>
  </p>



theme: jekyll-theme-minimal
