title: <p align="center"> Divya Singh </p>
logo: /assets/logo.png

 
  <br>  
  I'm currently working with SAP Labs and also doing a Executive PG Diploma in AI and ML with IIIT-B
  <br>
  </p>



theme: jekyll-theme-minimal
